// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJUJpJRW0IgYlN2ilThHpDMGtzx35g_Q',
    appId: '1:105288075569:web:1b81dcace2fd018604c810',
    messagingSenderId: '105288075569',
    projectId: 'ecommerce-e95c7',
    authDomain: 'ecommerce-e95c7.firebaseapp.com',
    storageBucket: 'ecommerce-e95c7.firebasestorage.app',
    measurementId: 'G-YV4XN15KSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxMlQsGujPICLtUXTRj7Do4mtf-xYwnDo',
    appId: '1:105288075569:android:f3f96aa01b13737c04c810',
    messagingSenderId: '105288075569',
    projectId: 'ecommerce-e95c7',
    storageBucket: 'ecommerce-e95c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOtU1F4n3TybZn9DoUMyKsQJDOt-y9K9k',
    appId: '1:105288075569:ios:21f9daa8910db20b04c810',
    messagingSenderId: '105288075569',
    projectId: 'ecommerce-e95c7',
    storageBucket: 'ecommerce-e95c7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOtU1F4n3TybZn9DoUMyKsQJDOt-y9K9k',
    appId: '1:105288075569:ios:21f9daa8910db20b04c810',
    messagingSenderId: '105288075569',
    projectId: 'ecommerce-e95c7',
    storageBucket: 'ecommerce-e95c7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJUJpJRW0IgYlN2ilThHpDMGtzx35g_Q',
    appId: '1:105288075569:web:9b7c2c9040da579c04c810',
    messagingSenderId: '105288075569',
    projectId: 'ecommerce-e95c7',
    authDomain: 'ecommerce-e95c7.firebaseapp.com',
    storageBucket: 'ecommerce-e95c7.firebasestorage.app',
    measurementId: 'G-G5PP8B43BQ',
  );
}
